global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: monitoring services
    static_configs:
      - targets:
        - 89.208.84.208:8081
        - 185.130.112.13:8081
        - 87.239.108.31:8081
  - job_name: monitoring system
    static_configs:
      - targets:
        - 89.208.84.208:9100
        - 185.130.112.13:9100
        - 87.239.108.31:9100