global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: monitoring
    static_configs:
      - targets:
        - 89.208.84.208:80
        - 185.130.112.13:80
        - 87.239.108.31:80